http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  auth:
    host: localhost
    paths: ['/auth/*']
  providers:
    host: localhost
    paths: ['/providers', '/providers/*', '/images-providers/*']
  events:
    host: localhost
    paths: ['/events', '/events/*', '/images-events/*']
  services:
    host: localhost
    paths: ['/services', '/services/*', '/images-services/*']
  notifications:
    host: localhost
    pats: ['/notifications', '/notifications/*']
serviceEndpoints:
  authServices:
    url: 'http://44.212.67.137'
  providersServices:
    url: 'http://3.86.233.169'
  eventsServices:
    url: 'http://3.82.252.105'
  servicesServices:
    url: 'http://44.211.46.169'
  notificationsServices:
    url: 'http://54.234.229.240'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  authPipeline:
    apiEndpoints:
      - auth
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authServices
              changeOrigin: true
  providersPipeline:
    apiEndpoints:
      - providers
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: providersServices
              changeOrigin: true
  eventsPipeline:
    apiEndpoints:
      - events
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: eventsServices
              changeOrigin: true
  servicesPipeline:
    apiEndpoints:
      - services
    policies:
      - proxy:
          - action:
              serviceEndpoint: servicesServices
              changeOrigin: true
  notificationsPipeline:
    apiEndpoints:
      - notifications
    policies:
      - proxy:
          - action:
              serviceEndpoint: notificationsServices
              changeOrigin: true